### ISSUE TITLE
ValueError: FrozenDict is immutable.

### ISSUE THREAD

**Issue by 007lbx** [seohongpark/ogbench#2]
There are some problem, when I train the hiql on --env_name=antmaze-large-navigate-v0:
Traceback (most recent call last):
  File "main.py", line 168, in <module>
    app.run(main)
  File "/mnt/Data_1/gk/miniconda3/envs/lbx/lib/python3.8/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/mnt/Data_1/gk/miniconda3/envs/lbx/lib/python3.8/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "main.py", line 83, in main
    agent = agent_class.create(
  File "/mnt/Data_1/gk/lbx/OG/impls/agents/hiql.py", line 314, in create
    params['modules_target_value'] = params['modules_value']
  File "/mnt/Data_1/gk/miniconda3/envs/lbx/lib/python3.8/site-packages/flax/core/frozen_dict.py", line 72, in __setitem__
    raise ValueError('FrozenDict is immutable.')
ValueError: FrozenDict is immutable.

**Comment by seohongpark** [comment]
I think it's likely a `flax` version issue. Perhaps try upgrading `flax` to the latest version (e.g., `flax>=0.8.5`)?
